""" Buff names """

buff_names = [
    "Major Aegis",
    "Minor Aegis",
    "Major Berserk",
    "Berserk",
    "Major Brutality",
    "Brutality",
    "Major Courage",
    "Minor Courage",
    "Minor Empower",
    "Major Endurance",
    "Minor Endurance",
    "Major Evasion",
    "Minor Evasion",
    "Major Expedition",
    "Minor Expedition",
    "Major Force",
    "Minor Force",
    "Major Fortitude",
    "Minor Fortitude",
    "Major Gallop",
    "Major Heroism",
    "Minor Heroism",
    "Major Intellect",
    "Minor Intellect",
    "Major Mending",
    "Minor Mending",
    "Physical Resistance",
    "Physical Resistance Potion",
    "Major Prophecy",
    "Minor Prophecy",
    "Major Protection",
    "Minor Protection",
    "Major Resolve",
    "Minor Resolve",
    "Major Savagery",
    "Minor Savagery",
    "Major Slayer",
    "Minor Slayer",
    "Major Sorcery",
    "Minor Sorcery",
    "Spell Resistance",
    "Spell Resistance Potion",
    "Minor Toughness",
    "Major Vitality",
    "Minor Vitality"
]