skills_names = ["Absorb",
"Absorb Missile",
"Absorption Field",
"Accelerated Growth",
"Accelerate",
"Accuracy",
"Accursed Charge",
"Acid Spray",
"Acrobat",
"Adrenaline Rush",
"Advanced Species",
"Aggressive Horn",
"Agility",
"Agony Totem",
"Ambush",
"Amphibian",
"Amplitude",
"Ancient Knowledge",
"Animate Blastbones",
"Annulment",
"Anti-Cavalry Caltrops",
"Antiquarian Insight",
"Arctic Blast",
"Arctic Wind",
"Argonian Resistance",
"Arrow Barrage",
"Arrow Spray",
"Arterial Burst",
"Ash Cloud",
"Ashlander",
"Aspect Improvement",
"Aspect of Terror",
"Assassin's Blade",
"Athletics",
"Augur",
"Aurora Javelin",
"Authority",
"Avid Boneyard",
"Backlash",
"Balanced Blade",
"Balanced Warrior",
"Balance",
"Ballista",
"Ball of Lightning",
"Banish the Wicked",
"Barbed Trap",
"Barrier",
"Battlefield Mobility",
"Battle Resurrection",
"Battle Roar",
"Battle Rush",
"Beckoning Armor",
"Berserker Rage",
"Berserker Strike",
"Betty Netch",
"Binding Javelin",
"Bird of Prey",
"Biting Jabs",
"Bitter Harvest",
"Blade Cloak",
"Blade of Woe",
"Blastbones",
"Blazing Shield",
"Blazing Spear",
"Blessing of Protection",
"Blessing Of Restoration",
"Blighted Blastbones",
"Blinding Flare",
"Blood Altar",
"Blood Craze",
"Blood for Blood",
"Blood Frenzy",
"Blood Magic",
"Blood Mist",
"Bloodmoon",
"Blood Rage",
"Blood Ritual",
"Blood Sacrifice",
"Blood Scion",
"Bloodthirst",
"Blue Betty",
"Blur",
"Bolstering Darkness",
"Bolt Escape",
"Bombard",
"Bond With Nature",
"Bone Armor",
"Bone Goliath Transformation",
"Bone Shield",
"Bone Surge",
"Bone Totem",
"Boneyard",
"Borrowed Time",
"Bound Aegis",
"Bound Armaments",
"Bound Armor",
"Boundless Storm",
"Bounty Hunter",
"Braided Tether",
"Brawler",
"Brawny",
"Breath of Life",
"Brewer",
"Brutal Pounce",
"Budding Seeds",
"Bull Netch",
"Burning Embers",
"Burning Heart",
"Burning Light",
"Burning Talons",
"Bursting Vines",
"Call of the Pack",
"Caltrops",
"Camouflaged Hunter",
"Capacitor",
"Carpentry",
"Carve",
"Catalyst",
"Cauterize",
"Channeled Acceleration",
"Channeled Focus",
"Charging Maneuver",
"Chef",
"Chemistry",
"Choking Talons",
"Cinder Storm",
"Circle of Protection",
"Clairvoyance",
"Claws of Anguish",
"Claws of Life",
"Cleanse",
"Cleansing Ritual",
"Cleave",
"Clemency",
"Coagulating Blood",
"Coalescence",
"Combat Frenzy",
"Combat Medic",
"Combat Prayer",
"Combustion",
"Concealed Weapon",
"Concentrated Barrier",
"Concentration",
"Conditioning",
"Conjured Ward",
"Connoisseur",
"Constitution",
"Consuming Darkness",
"Consuming Trap",
"Continuous Attack",
"Controlled Fury",
"Corpse Consumption",
"Corrosive Armor",
"Corrupting Pollen",
"Craftsman",
"Crescent Sweep",
"Cripple",
"Crippling Grasp",
"Critical Charge",
"Critical Rush",
"Critical Surge",
"Crushing Shock",
"Crushing Weapon",
"Crystal Fragments",
"Crystallized Shield",
"Crystallized Slab",
"Crystal Shard",
"Crystal Weapon",
"Curative Curse",
"Cutpurse",
"Cutting Dive",
"Cycle of Life",
"Daedric Curse",
"Daedric Minefield",
"Daedric Mines",
"Daedric Prey",
"Daedric Protection",
"Daedric Tomb",
"Dampen Magic",
"Dark Cloak",
"Dark Conversion",
"Dark Deal",
"Dark Exchange",
"Dark Flare",
"Dark Shade",
"Dark Stalker",
"Dark Talons",
"Dark Veil",
"Dark Vigor",
"Dawnbreaker",
"Dawnbreaker of Smiting",
"Deaden Pain",
"Deadly Bash",
"Deadly Cloak",
"Deafening Roar",
"Death Gleaning",
"Death Knell",
"Death Scythe",
"Death Stroke",
"Debilitate",
"Deceptive Predator",
"Deep Breath",
"Deep Fissure",
"Deep Slash",
"Deep Thoughts",
"Defensive Posture",
"Defensive Rune",
"Defensive Stance",
"Deflect Bolts",
"Degeneration",
"Deliberation",
"Destruction Expert",
"Destructive Clench",
"Destructive Reach",
"Destructive Touch",
"Detonating Siphon",
"Devour",
"Dexterity",
"Dilation",
"Diplomat",
"Disdain Harm",
"Dismember",
"Dive",
"Dizzying Swing",
"Domination",
"Dragon Blood",
"Dragon Fire Scale",
"Dragonknight Standard",
"Dragon Leap",
"Draining Shot",
"Drain Power",
"Drain Vigor",
"Draw Essence",
"Dual Wield Expert",
"Dynamic",
"Echoing Vigor",
"Eclipse",
"Efficient Purge",
"Elder Dragon",
"Elemental Blockade",
"Elemental Drain",
"Elemental Force",
"Elemental Rage",
"Elemental Ring",
"Elemental Storm",
"Elemental Susceptibility",
"Elemental Talent",
"Elemental Weapon",
"Elude",
"Elusive Mist",
"Emerald Moss",
"Emperor",
"Empowered Ward",
"Empowering Chains",
"Empowering Grasp",
"Empowering Sweep",
"Encase",
"Enchanted Forest",
"Enchanted Growth",
"Endless Fury",
"Endless Hail",
"Enduring Rays",
"Enduring Undeath",
"Energized",
"Energy Orb",
"Energy Overload",
"Engraver",
"Engulfing Flames",
"Entropy",
"Equilibrium",
"Eruption",
"Essence Drain",
"Eternal Guardian",
"Eternal Mountain",
"Evasion",
"Everlasting Magic",
"Evil Hunter",
"Eviscerate",
"Evocation",
"Excavator's Reserves",
"Executioner",
"Exhilarating Drain",
"Expansive Frost Cloak",
"Expert Hunter",
"Expert Mage",
"Expert Summoner",
"Exploitation",
"Explosive Charge",
"Expunge and Modify",
"Expunge",
"Extended Ritual",
"Eye of the Storm",
"Falcon's Swiftness",
"Farsight",
"Feed",
"Feline Ambush",
"Feral Guardian",
"Feral Pounce",
"Ferocious Leap",
"Ferocious Roar",
"Fetcher Infection",
"Fiery Breath",
"Fiery Grip",
"Finders Keepers",
"Fire Rune",
"Flame Lash",
"Flame Skull",
"Flames of Oblivion",
"Flawless Dawnbreaker",
"Flourish",
"Flurry",
"Flying Blade",
"Focused Aim",
"Focused Charge",
"Follow Up",
"Forceful",
"Force Pulse",
"Force Shock",
"Force Siphon",
"Fortress",
"Forward Momentum",
"Fossilize",
"Fragmented Shield",
"Frost Cloak",
"Frozen Armor",
"Frozen Colossus",
"Frozen Device",
"Frozen Gate",
"Frozen Retreat",
"Fungal Growth",
"Funnel Health",
"Future Focus",
"Ghostly Embrace",
"Gift of Magnus",
"Glacial Colossus",
"Glacial Presence",
"Gourmand",
"Grace",
"Grand Healing",
"Grave Grasp",
"Greater Storm Atronach",
"Green Dragon Blood",
"Green Lotus",
"Grim Focus",
"Gripping Shards",
"Growing Swarm",
"Guard",
"Haggling",
"Hand Brush",
"Hardened Armor",
"Hardened Ward",
"Harness Magicka",
"Hasty Prayer",
"Hasty Retreat",
"Haunting Curse",
"Hawk Eye",
"Healing Ritual",
"Healing Seed",
"Healing Springs",
"Healing Thicket",
"Healing Ward",
"Health Avarice",
"Healthy Offering",
"Heavy Armor Bonuses",
"Heavy Armor Penalties",
"Heavy Shovel",
"Heavy Weapons",
"Helping Hands",
"Hemorrhage",
"Heroic Slash",
"Hexproof",
"Hidden Blade",
"Highborn",
"Hircine's Bounty",
"Hircine's Fortitude",
"Hircine's Rage",
"Hireling",
"Honor The Dead",
"Howl of Agony",
"Howl of Despair",
"Hungry Scythe",
"Hunter's Eye",
"Hurricane",
"Hypnosis",
"Ice Comet",
"Ice Fortress",
"Icy Aura",
"Igneous Shield",
"Igneous Weapons",
"Illuminate",
"Illustrious Healing",
"Imbue Weapon",
"Immovable",
"Impale",
"Impaling Shards",
"Imperial Mettle",
"Improved Hiding",
"Improved Sneak",
"Impulse",
"Incapacitating Strike",
"Inevitable Detonation",
"Infectious Claws",
"Inferno",
"Inhale",
"Inner Beast",
"Inner Fire",
"Inner Light",
"Inner Rage",
"Intensive Mender",
"Intimidating Presence",
"Introspection",
"Invasion",
"Iron Skin",
"Jewelry Extraction",
"Juggernaut",
"Keen Eye: Cloth",
"Keen Eye: Dig Sites",
"Keen Eye: Jewelry",
"Keen Eye: Ore",
"Keen Eye: Reagents",
"Keen Eye: Rune Stones",
"Keen Eye: Treasure Chests",
"Keen Eye: Wood",
"Kickback",
"Killer's Blade",
"Laboratory Use",
"Lacerate",
"Lapidary Research",
"Last Gasp",
"Lava Whip",
"Leeching Strikes",
"Leeching Vines",
"Lethal Arrow",
"Life amid Death",
"Life Giver",
"Life Mender",
"Light Armor Bonuses",
"Light Armor Penalties",
"Light Fingers",
"Lightning Flood",
"Lightning Form",
"Lightning Splash",
"Light's Champion",
"Light Weaver",
"Lightweight Beast Trap",
"Lingering Flare",
"Liquid Lightning",
"Living Dark",
"Living Trellis",
"Living Vines",
"Locksmith",
"Long Shots",
"Lotus Blossom",
"Lotus Fan",
"Lotus Flower",
"Low Slash",
"Lumberjack Hireling",
"Luminous Shards",
"Lunar Blessings",
"Mage Adept",
"Magelight",
"Mages' Fury",
"Mages' Wrath",
"Magicka Aid",
"Magicka Controller",
"Magicka Detonation",
"Magicka Flood",
"Magicka Mastery",
"Magma Armor",
"Magma Shell",
"Magnum Shot",
"Malacath's Vengeance",
"Malevolent Offering",
"Manifestation of Terror",
"Mark Target",
"Martial Training",
"Mass Hysteria",
"Master Assassin",
"Master Ritualist",
"Maturation",
"Medicinal Use",
"Meditate",
"Medium Armor Bonuses",
"Mending",
"Mend Spirit",
"Mend Wounds",
"Merciless Resolve",
"Mesmerize",
"Metal Extraction",
"Metallurgy",
"Metalworking",
"Meteor",
"Might of the Guild",
"Miner Hireling",
"Mirage",
"Mist Form",
"Molten Armaments",
"Molten Weapons",
"Molten Whip",
"Momentum",
"Monarch",
"Mortal Coil",
"Mountain's Blessing",
"Mystic Guard",
"Mystic Orb",
"Mystic Siphon",
"Nature's Embrace",
"Nature's Gift",
"Nature's Grasp",
"Near-Death Experience",
"Necrotic Orb",
"Necrotic Potency",
"Negate Magic",
"Northern Storm",
"Nova",
"Noxious Breath",
"Obsidian Shard",
"Obsidian Shield",
"Onslaught",
"Opportunist",
"Outfitter Hireling",
"Overflowing Altar",
"Overload",
"Pack Leader",
"Padomaic Sprint",
"Panacea",
"Pariah's Resolve",
"Path of Darkness",
"Penetrating Magic",
"Perfect Scion",
"Permafrost",
"Persistence",
"Persuasive Will",
"Pestilent Colossus",
"Petrify",
"Phantasmal Escape",
"Pierce Armor",
"Piercing Cold",
"Piercing Howl",
"Piercing Javelin",
"Piercing Mark",
"Piercing Spear",
"Platings Expertise",
"Poison Arrow",
"Poison Injection",
"Polar Wind",
"Potency Improvement",
"Pounce",
"Power Bash",
"Power Extraction",
"Power of the Light",
"Power Overload",
"Power Slam",
"Power Stone",
"Power Surge",
"Practiced Incantation",
"Precognition",
"Preemptive Power",
"Pressure Points",
"Prism",
"Prodigy",
"Propelling Shield",
"Protective Plate",
"Protective Scale",
"Proximity Detonation",
"Pulsar",
"Pummeling Goliath",
"Puncture",
"Puncturing Strikes",
"Puncturing Sweep",
"Purge",
"Purifying Light",
"Pursuit",
"Quick Cloak",
"Quick Siphon",
"Race Against Time",
"Radial Sweep",
"Radiant Aura",
"Radiant Destruction",
"Radiant Glory",
"Radiant Magelight",
"Radiant Oppression",
"Radiant Ward",
"Radiating Regeneration",
"Rally",
"Ranger",
"Ransack",
"Rapid Fire",
"Rapid Maneuver",
"Rapid Mending",
"Rapid Regeneration",
"Rapid Rot",
"Rapid Strikes",
"Ravenous Goliath",
"Razor Caltrops",
"Reach",
"Reanimate",
"Reaper's Mark",
"Rebate",
"Recipe Improvement",
"Recipe Quality",
"Red Diamond",
"Reflective Light",
"Refreshing Path",
"Refreshing Shadows",
"Regeneration",
"Relentless Focus",
"Remembrance",
"Remote Totem",
"Render Flesh",
"Rending Slashes",
"Rend",
"Renewing Animation",
"Renewing Undeath",
"Repentance",
"Replenishing Barrier",
"Resin Expertise",
"Resist Affliction",
"Resistant Flesh",
"Resist Flame",
"Resist Frost",
"Resolve",
"Resolving Vigor",
"Resourceful",
"Restoration Expert",
"Restoration Master",
"Restoring Aura",
"Restoring Focus",
"Restoring Spirit",
"Restoring Tether",
"Restraining Prison",
"Retreating Maneuver",
"Reusable Parts",
"Revealing Flare",
"Reveler",
"Reverberating Bash",
"Reverse Slash",
"Reverse Slice",
"Revitalize",
"Reviving Barrier",
"Ricochet Skull",
"Ring of Preservation",
"Rite of Passage",
"Ritual of Rebirth",
"Ritual of Retribution",
"Roar",
"Robustness",
"Rourken's Rebuke",
"Ruffian",
"Rugged",
"Ruination",
"Ruinous Cyclone",
"Ruinous Scythe",
"Rune Cage",
"Rune Focus",
"Rune Prison",
"Runestone Extraction",
"Rushed Ceremony",
"Sacred Ground",
"Sanguine Altar",
"Sap Essence",
"Sated Fury",
"Savage Beast",
"Savage Strength",
"Scalding Rune",
"Scaled Armor",
"Scales of Pitiless Justice",
"Scatter Shot",
"Scorch",
"Screaming Cliff Racer",
"Scrier's Patience",
"Scry",
"Searing Heat",
"Searing Strike",
"Secluded Grove",
"See the Unseen",
"Shadow Barrier",
"Shadow Cloak",
"Shadow Image",
"Shadow Rider",
"Shadow Silk",
"Shadowy Disguise",
"Shadowy Supplier",
"Shattering Prison",
"Shattering Rocks",
"Shatter Soul",
"Shield Charge",
"Shield Discipline",
"Shielded Assault",
"Shield Wall",
"Shifting Standard",
"Shimmering Shield",
"Shocking Siphon",
"Shooting Star",
"Shrewd Offering",
"Shrouded Daggers",
"Shuffle",
"Siege Shield",
"Siege Weapon Shield",
"Silver Bolts",
"Silver Leash",
"Silver Shards",
"Simmering Frenzy",
"Siphoning Attacks",
"Siphoning Strikes",
"Siphon Spirit",
"Skeletal Arcanist",
"Skeletal Archer",
"Skeletal Mage",
"Skilled Tracker",
"Slaughter",
"Slayer",
"Sleet Storm",
"Snakeblood",
"Snipe",
"Solar Barrage",
"Solar Disturbance",
"Solar Flare",
"Solar Prison",
"Solvent Proficiency",
"Soothing Spores",
"Soul Assault",
"Soul Harvest",
"Soul Lock",
"Soul Shatter",
"Soul Shred",
"Soul Siphoner",
"Soul Siphon",
"Soul Splitting Trap",
"Soul Strike",
"Soul Summons",
"Soul Tether",
"Soul Trap",
"Spear Shards",
"Spear Wall",
"Spectral Assassin",
"Spell Attunement",
"Spell Orb",
"Spell Recharge",
"Spell Symmetry",
"Spell Wall",
"Spell Warding",
"Spiked Armor",
"Spiked Bone Shield",
"Spirit Guardian",
"Spirit Mender",
"Stalking Blastbones",
"Stalwart Guard",
"Stalwart",
"Stampede",
"Standard of Might",
"Steadfast Ward",
"Steel Tornado",
"Stitching",
"Stonefist",
"Stone Giant",
"Streak",
"Strife",
"Strike from the Shadows",
"Structured Entropy",
"Stupefy",
"Sturdy Horn",
"Subterranean Assault",
"Summon Charged Atronach",
"Summoner's Armor",
"Summon Shade",
"Summon Storm Atronach",
"Summon Twilight Matriarch",
"Summon Twilight Tormentor",
"Summon Unstable Clannfear",
"Summon Unstable Familiar",
"Summon Volatile Familiar",
"Summon Winged Twilight",
"Sundering Swing",
"Sun Fire",
"Sun Shield",
"Suppression Field",
"Surge",
"Surprise Attack",
"Swallow Soul",
"Swarming Scion",
"Swarm",
"Swiftly Forgotten",
"Swift Warrior",
"Sword and Board",
"Symbiosis",
"Syrabane's Boon",
"Tactician",
"Tailoring",
"Take Flight",
"Tangling Webs",
"Tannin Expertise",
"Teleport Strike",
"Temper Expertise",
"Temporal Guard",
"Thrive in Chaos",
"Time Freeze",
"Timely Escape",
"Time Stop",
"Toppling Charge",
"Tough",
"Toxic Barrage",
"Trafficker",
"Transfer",
"Trap Beast",
"Trapping Webs",
"Tri Focus",
"Trowel",
"Turn Evil",
"Twin Blade and Blunt",
"Twin Slashes",
"Twisting Path",
"Undaunted Command",
"Undaunted Mettle",
"Undead Confederate",
"Undeath",
"Undo",
"Unflinching Rage",
"Unholy Knowledge",
"Unnatural Movement",
"Unnerving Boneyard",
"Unraveling",
"Unrelenting Grip",
"Unstable Core",
"Unstable Wall of Elements",
"Unstoppable Brute",
"Unstoppable",
"Uppercut",
"Vampire's Bane",
"Vampiric Drain",
"Veiled Strike",
"Veil of Blades",
"Veil of Shadows",
"Venom Arrow",
"Venomous Claw",
"Venom Skull",
"Vigor",
"Volatile Armor",
"Volcanic Rune",
"Volley",
"Wall of Elements",
"Ward Ally",
"War Horn",
"Warmth",
"Wayfarer",
"Weakness to Elements",
"Werewolf Berserker",
"Werewolf Transformation",
"Whirling Blades",
"Whirlwind",
"Wild Guardian",
"Wind Walker",
"Winter's Revenge",
"Wood Extraction",
"Woodworking",
"World in Ruin",
"Wrecking Blow",
"Y'ffre's Endurance"]